server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # 后端接口代理
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 上传图片静态访问
    location /uploads/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    # Vue Router 前端路由
    location / {
        try_files $uri $uri/ /index.html;
    }
}
